/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as JudgeRouteImport } from './routes/judge'
import { Route as LoginRouteImport } from './routes/login'
import { Route as JudgeIndexRouteImport } from './routes/judge.index'
import { Route as JudgeAnalyticsRouteImport } from './routes/judge.analytics'
import { Route as JudgeClustersRouteImport } from './routes/judge.clusters'
import { Route as JudgeEvaluationsRouteImport } from './routes/judge.evaluations'
import { Route as JudgeGemsRouteImport } from './routes/judge.gems'
import { Route as JudgeLandscapeRouteImport } from './routes/judge.landscape'
import { Route as JudgeQueueRouteImport } from './routes/judge.queue'
import { Route as OrganizerIndexRouteImport } from './routes/organizer.index'
import { Route as OrganizerAnalyticsRouteImport } from './routes/organizer.analytics'
import { Route as OrganizerJudgesRouteImport } from './routes/organizer.judges'
import { Route as OrganizerSettingsRouteImport } from './routes/organizer.settings'
import { Route as OrganizerSubmissionsRouteImport } from './routes/organizer.submissions'
import { Route as ParticipantIndexRouteImport } from './routes/participant.index'
import { Route as JudgeSubmissionsIndexRouteImport } from './routes/judge.submissions.index'
import { Route as JudgeSubmissionsIdRouteImport } from './routes/judge.submissions.$id'
import { Route as OrganizerCompetitionsIndexRouteImport } from './routes/organizer.competitions.index'
import { Route as OrganizerCompetitionsNewRouteImport } from './routes/organizer.competitions.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const JudgeRoute = JudgeRouteImport.update({
  id: '/judge',
  path: '/judge',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const JudgeIndexRoute = JudgeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => JudgeRoute,
} as any)
const JudgeAnalyticsRoute = JudgeAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => JudgeRoute,
} as any)
const JudgeClustersRoute = JudgeClustersRouteImport.update({
  id: '/clusters',
  path: '/clusters',
  getParentRoute: () => JudgeRoute,
} as any)
const JudgeEvaluationsRoute = JudgeEvaluationsRouteImport.update({
  id: '/evaluations',
  path: '/evaluations',
  getParentRoute: () => JudgeRoute,
} as any)
const JudgeGemsRoute = JudgeGemsRouteImport.update({
  id: '/gems',
  path: '/gems',
  getParentRoute: () => JudgeRoute,
} as any)
const JudgeLandscapeRoute = JudgeLandscapeRouteImport.update({
  id: '/landscape',
  path: '/landscape',
  getParentRoute: () => JudgeRoute,
} as any)
const JudgeQueueRoute = JudgeQueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => JudgeRoute,
} as any)
const OrganizerIndexRoute = OrganizerIndexRouteImport.update({
  id: '/organizer/',
  path: '/organizer/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizerAnalyticsRoute = OrganizerAnalyticsRouteImport.update({
  id: '/organizer/analytics',
  path: '/organizer/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizerJudgesRoute = OrganizerJudgesRouteImport.update({
  id: '/organizer/judges',
  path: '/organizer/judges',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizerSettingsRoute = OrganizerSettingsRouteImport.update({
  id: '/organizer/settings',
  path: '/organizer/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizerSubmissionsRoute = OrganizerSubmissionsRouteImport.update({
  id: '/organizer/submissions',
  path: '/organizer/submissions',
  getParentRoute: () => rootRouteImport,
} as any)
const ParticipantIndexRoute = ParticipantIndexRouteImport.update({
  id: '/participant/',
  path: '/participant/',
  getParentRoute: () => rootRouteImport,
} as any)
const JudgeSubmissionsIndexRoute = JudgeSubmissionsIndexRouteImport.update({
  id: '/submissions/',
  path: '/submissions/',
  getParentRoute: () => JudgeRoute,
} as any)
const JudgeSubmissionsIdRoute = JudgeSubmissionsIdRouteImport.update({
  id: '/submissions/$id',
  path: '/submissions/$id',
  getParentRoute: () => JudgeRoute,
} as any)
const OrganizerCompetitionsIndexRoute =
  OrganizerCompetitionsIndexRouteImport.update({
    id: '/organizer/competitions/',
    path: '/organizer/competitions/',
    getParentRoute: () => rootRouteImport,
  } as any)
const OrganizerCompetitionsNewRoute =
  OrganizerCompetitionsNewRouteImport.update({
    id: '/organizer/competitions/new',
    path: '/organizer/competitions/new',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/judge': typeof JudgeRouteWithChildren
  '/login': typeof LoginRoute
  '/judge/analytics': typeof JudgeAnalyticsRoute
  '/judge/clusters': typeof JudgeClustersRoute
  '/judge/evaluations': typeof JudgeEvaluationsRoute
  '/judge/gems': typeof JudgeGemsRoute
  '/judge/landscape': typeof JudgeLandscapeRoute
  '/judge/queue': typeof JudgeQueueRoute
  '/organizer/analytics': typeof OrganizerAnalyticsRoute
  '/organizer/judges': typeof OrganizerJudgesRoute
  '/organizer/settings': typeof OrganizerSettingsRoute
  '/organizer/submissions': typeof OrganizerSubmissionsRoute
  '/judge/': typeof JudgeIndexRoute
  '/organizer/': typeof OrganizerIndexRoute
  '/participant/': typeof ParticipantIndexRoute
  '/judge/submissions/$id': typeof JudgeSubmissionsIdRoute
  '/organizer/competitions/new': typeof OrganizerCompetitionsNewRoute
  '/judge/submissions/': typeof JudgeSubmissionsIndexRoute
  '/organizer/competitions/': typeof OrganizerCompetitionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/login': typeof LoginRoute
  '/judge/analytics': typeof JudgeAnalyticsRoute
  '/judge/clusters': typeof JudgeClustersRoute
  '/judge/evaluations': typeof JudgeEvaluationsRoute
  '/judge/gems': typeof JudgeGemsRoute
  '/judge/landscape': typeof JudgeLandscapeRoute
  '/judge/queue': typeof JudgeQueueRoute
  '/organizer/analytics': typeof OrganizerAnalyticsRoute
  '/organizer/judges': typeof OrganizerJudgesRoute
  '/organizer/settings': typeof OrganizerSettingsRoute
  '/organizer/submissions': typeof OrganizerSubmissionsRoute
  '/judge': typeof JudgeIndexRoute
  '/organizer': typeof OrganizerIndexRoute
  '/participant': typeof ParticipantIndexRoute
  '/judge/submissions/$id': typeof JudgeSubmissionsIdRoute
  '/organizer/competitions/new': typeof OrganizerCompetitionsNewRoute
  '/judge/submissions': typeof JudgeSubmissionsIndexRoute
  '/organizer/competitions': typeof OrganizerCompetitionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/judge': typeof JudgeRouteWithChildren
  '/login': typeof LoginRoute
  '/judge/analytics': typeof JudgeAnalyticsRoute
  '/judge/clusters': typeof JudgeClustersRoute
  '/judge/evaluations': typeof JudgeEvaluationsRoute
  '/judge/gems': typeof JudgeGemsRoute
  '/judge/landscape': typeof JudgeLandscapeRoute
  '/judge/queue': typeof JudgeQueueRoute
  '/organizer/analytics': typeof OrganizerAnalyticsRoute
  '/organizer/judges': typeof OrganizerJudgesRoute
  '/organizer/settings': typeof OrganizerSettingsRoute
  '/organizer/submissions': typeof OrganizerSubmissionsRoute
  '/judge/': typeof JudgeIndexRoute
  '/organizer/': typeof OrganizerIndexRoute
  '/participant/': typeof ParticipantIndexRoute
  '/judge/submissions/$id': typeof JudgeSubmissionsIdRoute
  '/organizer/competitions/new': typeof OrganizerCompetitionsNewRoute
  '/judge/submissions/': typeof JudgeSubmissionsIndexRoute
  '/organizer/competitions/': typeof OrganizerCompetitionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/demo'
    | '/judge'
    | '/login'
    | '/judge/analytics'
    | '/judge/clusters'
    | '/judge/evaluations'
    | '/judge/gems'
    | '/judge/landscape'
    | '/judge/queue'
    | '/organizer/analytics'
    | '/organizer/judges'
    | '/organizer/settings'
    | '/organizer/submissions'
    | '/judge/'
    | '/organizer/'
    | '/participant/'
    | '/judge/submissions/$id'
    | '/organizer/competitions/new'
    | '/judge/submissions/'
    | '/organizer/competitions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/demo'
    | '/login'
    | '/judge/analytics'
    | '/judge/clusters'
    | '/judge/evaluations'
    | '/judge/gems'
    | '/judge/landscape'
    | '/judge/queue'
    | '/organizer/analytics'
    | '/organizer/judges'
    | '/organizer/settings'
    | '/organizer/submissions'
    | '/judge'
    | '/organizer'
    | '/participant'
    | '/judge/submissions/$id'
    | '/organizer/competitions/new'
    | '/judge/submissions'
    | '/organizer/competitions'
  id:
    | '__root__'
    | '/'
    | '/demo'
    | '/judge'
    | '/login'
    | '/judge/analytics'
    | '/judge/clusters'
    | '/judge/evaluations'
    | '/judge/gems'
    | '/judge/landscape'
    | '/judge/queue'
    | '/organizer/analytics'
    | '/organizer/judges'
    | '/organizer/settings'
    | '/organizer/submissions'
    | '/judge/'
    | '/organizer/'
    | '/participant/'
    | '/judge/submissions/$id'
    | '/organizer/competitions/new'
    | '/judge/submissions/'
    | '/organizer/competitions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DemoRoute: typeof DemoRoute
  JudgeRoute: typeof JudgeRouteWithChildren
  LoginRoute: typeof LoginRoute
  OrganizerAnalyticsRoute: typeof OrganizerAnalyticsRoute
  OrganizerJudgesRoute: typeof OrganizerJudgesRoute
  OrganizerSettingsRoute: typeof OrganizerSettingsRoute
  OrganizerSubmissionsRoute: typeof OrganizerSubmissionsRoute
  OrganizerIndexRoute: typeof OrganizerIndexRoute
  ParticipantIndexRoute: typeof ParticipantIndexRoute
  OrganizerCompetitionsNewRoute: typeof OrganizerCompetitionsNewRoute
  OrganizerCompetitionsIndexRoute: typeof OrganizerCompetitionsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/judge': {
      id: '/judge'
      path: '/judge'
      fullPath: '/judge'
      preLoaderRoute: typeof JudgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/judge/': {
      id: '/judge/'
      path: '/'
      fullPath: '/judge/'
      preLoaderRoute: typeof JudgeIndexRouteImport
      parentRoute: typeof JudgeRoute
    }
    '/judge/analytics': {
      id: '/judge/analytics'
      path: '/analytics'
      fullPath: '/judge/analytics'
      preLoaderRoute: typeof JudgeAnalyticsRouteImport
      parentRoute: typeof JudgeRoute
    }
    '/judge/clusters': {
      id: '/judge/clusters'
      path: '/clusters'
      fullPath: '/judge/clusters'
      preLoaderRoute: typeof JudgeClustersRouteImport
      parentRoute: typeof JudgeRoute
    }
    '/judge/evaluations': {
      id: '/judge/evaluations'
      path: '/evaluations'
      fullPath: '/judge/evaluations'
      preLoaderRoute: typeof JudgeEvaluationsRouteImport
      parentRoute: typeof JudgeRoute
    }
    '/judge/gems': {
      id: '/judge/gems'
      path: '/gems'
      fullPath: '/judge/gems'
      preLoaderRoute: typeof JudgeGemsRouteImport
      parentRoute: typeof JudgeRoute
    }
    '/judge/landscape': {
      id: '/judge/landscape'
      path: '/landscape'
      fullPath: '/judge/landscape'
      preLoaderRoute: typeof JudgeLandscapeRouteImport
      parentRoute: typeof JudgeRoute
    }
    '/judge/queue': {
      id: '/judge/queue'
      path: '/queue'
      fullPath: '/judge/queue'
      preLoaderRoute: typeof JudgeQueueRouteImport
      parentRoute: typeof JudgeRoute
    }
    '/organizer/': {
      id: '/organizer/'
      path: '/organizer'
      fullPath: '/organizer/'
      preLoaderRoute: typeof OrganizerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizer/analytics': {
      id: '/organizer/analytics'
      path: '/organizer/analytics'
      fullPath: '/organizer/analytics'
      preLoaderRoute: typeof OrganizerAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizer/judges': {
      id: '/organizer/judges'
      path: '/organizer/judges'
      fullPath: '/organizer/judges'
      preLoaderRoute: typeof OrganizerJudgesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizer/settings': {
      id: '/organizer/settings'
      path: '/organizer/settings'
      fullPath: '/organizer/settings'
      preLoaderRoute: typeof OrganizerSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizer/submissions': {
      id: '/organizer/submissions'
      path: '/organizer/submissions'
      fullPath: '/organizer/submissions'
      preLoaderRoute: typeof OrganizerSubmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/participant/': {
      id: '/participant/'
      path: '/participant'
      fullPath: '/participant/'
      preLoaderRoute: typeof ParticipantIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/judge/submissions/': {
      id: '/judge/submissions/'
      path: '/submissions'
      fullPath: '/judge/submissions/'
      preLoaderRoute: typeof JudgeSubmissionsIndexRouteImport
      parentRoute: typeof JudgeRoute
    }
    '/judge/submissions/$id': {
      id: '/judge/submissions/$id'
      path: '/submissions/$id'
      fullPath: '/judge/submissions/$id'
      preLoaderRoute: typeof JudgeSubmissionsIdRouteImport
      parentRoute: typeof JudgeRoute
    }
    '/organizer/competitions/': {
      id: '/organizer/competitions/'
      path: '/organizer/competitions'
      fullPath: '/organizer/competitions/'
      preLoaderRoute: typeof OrganizerCompetitionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizer/competitions/new': {
      id: '/organizer/competitions/new'
      path: '/organizer/competitions/new'
      fullPath: '/organizer/competitions/new'
      preLoaderRoute: typeof OrganizerCompetitionsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface JudgeRouteChildren {
  JudgeAnalyticsRoute: typeof JudgeAnalyticsRoute
  JudgeClustersRoute: typeof JudgeClustersRoute
  JudgeEvaluationsRoute: typeof JudgeEvaluationsRoute
  JudgeGemsRoute: typeof JudgeGemsRoute
  JudgeLandscapeRoute: typeof JudgeLandscapeRoute
  JudgeQueueRoute: typeof JudgeQueueRoute
  JudgeIndexRoute: typeof JudgeIndexRoute
  JudgeSubmissionsIdRoute: typeof JudgeSubmissionsIdRoute
  JudgeSubmissionsIndexRoute: typeof JudgeSubmissionsIndexRoute
}

const JudgeRouteChildren: JudgeRouteChildren = {
  JudgeAnalyticsRoute: JudgeAnalyticsRoute,
  JudgeClustersRoute: JudgeClustersRoute,
  JudgeEvaluationsRoute: JudgeEvaluationsRoute,
  JudgeGemsRoute: JudgeGemsRoute,
  JudgeLandscapeRoute: JudgeLandscapeRoute,
  JudgeQueueRoute: JudgeQueueRoute,
  JudgeIndexRoute: JudgeIndexRoute,
  JudgeSubmissionsIdRoute: JudgeSubmissionsIdRoute,
  JudgeSubmissionsIndexRoute: JudgeSubmissionsIndexRoute,
}

const JudgeRouteWithChildren = JudgeRoute._addFileChildren(JudgeRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DemoRoute: DemoRoute,
  JudgeRoute: JudgeRouteWithChildren,
  LoginRoute: LoginRoute,
  OrganizerAnalyticsRoute: OrganizerAnalyticsRoute,
  OrganizerJudgesRoute: OrganizerJudgesRoute,
  OrganizerSettingsRoute: OrganizerSettingsRoute,
  OrganizerSubmissionsRoute: OrganizerSubmissionsRoute,
  OrganizerIndexRoute: OrganizerIndexRoute,
  ParticipantIndexRoute: ParticipantIndexRoute,
  OrganizerCompetitionsNewRoute: OrganizerCompetitionsNewRoute,
  OrganizerCompetitionsIndexRoute: OrganizerCompetitionsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
